format_version: 3
pipelines:
  i-build-it-i-run-it:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/mansab/serverspec-container-tests.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - I did run
                command: echo
                run_if: passed
